<?php

/**
 * @file
 * Hooks and preprocess functions for search_api_opensolr_security module.
 */

use Drupal\search_api_opensolr_security\ServerSecurityOperations;
use Drupal\Core\Entity\EntityInterface;
use Drupal\search_api\ServerInterface;

/**
 * Implements hook_entity_operation().
 */
function search_api_opensolr_security_entity_operation(EntityInterface $entity) {
  if ($entity instanceof ServerInterface) {
    return \Drupal::service('class_resolver')
      ->getInstanceFromDefinition(ServerSecurityOperations::class)
      ->entityOperation($entity);
  }
  return [];
}
